server:
  port: 8080

spring :

  # Database setting
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: chocobar
      password: ssafy
    url: jdbc:mysql://j9d109.p.ssafy.io/mydb?useUniCode=yes&characterEncoding=UTF-8

  # JPA setting
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
#    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendingemail204@gmail.com
    password: dzqmwcpoosxferox
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

# hibernate logging
logging:
  level:
    org:
      hibernate: info

# JWT setting
jwt:
  secretKey:
    uptriewucb89fjckwewejhwe37dhcvvmxdsjwuiurhm5ffwfregyutjregyuwhjiquxyd32ctvgbbfgdteeyggdaxccxewrtfdefrgvxcxsdikjme43gbj7gcf6tg64sfjioxjd
  access:
    expiration: 100000000
    header: Authorization
  refresh:
    # 2 week expiration
    expiration: 129600000
    header: Authorization-refresh

# choco bank base_url
request:
  chocobank:
    base_url: http://localhost:8001