# Generated by Django 4.2.5 on 2023-09-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplendorInfo',
        ),
        migrations.DeleteModel(
            name='SplendorRoomcode',
        ),
        migrations.DeleteModel(
            name='SplendorServer',
        ),
    ]
