
server:
  port: 8001

spring :
  # Database setting
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ssafy
    url: jdbc:mysql://localhost:3306/mydb?useUniCode=yes&characterEncoding=UTF-8

  # JPA setting
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  #    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendingemail204@gmail.com
    password: dzqmwcpoosxferox
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  # Swagger Setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# hibernate logging
logging:
  level:
    org:
      hibernate: info

# JWT setting
jwt:
  secretKey:
    uptriewucbckckdcshlftsjgjcohwnwo0h9b7xnskdl1alagvpcvllq427d8xjkflejeleodhxzppsaiwhr3k46nmmvcjdzsi8r32jjhxdjkjsdagqygzcmfglfhpidikjme43gbj7gcf6tg64sfjioxjd
  access:
    expiration: 1000000
    header: Authorization
  refresh:
    # 2 week expiration
    expiration: 129600000
    header: Authorization-refresh
